catalog:
  "@testing-library/dom": latest
  "@testing-library/jest-dom": latest
  "@testing-library/react": latest
  "@tailwindcss/postcss": latest
  "@types/node": latest
  "@types/react": latest
  "@types/react-dom": latest
  "@types/jest": latest
  nuqs: latest
  eslint: latest
  eslint-config-next: latest
  next: latest
  react: latest
  react-dom: latest
  tailwindcss: latest
  typescript: latest
  jest: latest
  jest-environment-jsdom: latest
  ts-node: latest
  ts-jest: latest

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
