catalog:
  "@tailwindcss/postcss": latest
  "@types/node": latest
  "@types/react": latest
  "@types/react-dom": latest
  nuqs: latest
  eslint: latest
  eslint-config-next: latest
  next: latest
  react: latest
  react-dom: latest
  tailwindcss: latest
  typescript: latest

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
