import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const geistOnest = Onest({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistOnest.variable} antialiased`}>{children}</body>
    </html>
  );
}
